### ISSUE TITLE
VSCode & SCSS / Sass - Autocompletion / Suggestions

### ISSUE THREAD

**Issue by nikbrunner** [UnwrittenFun/svelte-vscode#110]
Hi there,

so I am working on a personal Svelte Setup, for which I want to use Svelte ( Not Sapper ), SCSS and Autoprefixer. I checked and followed different Instructions and also got it to work. I get no errors, and my Scss gets compiled with Prefixes. But I have one problem and didn't find any solution or other issues related to this. 

## The issue

Usually, when writing SCSS,  I get suggestions / auto-completion from VSCode. But here in my context, I don't get these. The variables and includes from the mixins work, but I practically have to type them out of memory, which is of course not very comfortable. See here:

![style-tag](https://user-images.githubusercontent.com/46924729/79115812-269b7280-7d87-11ea-88e2-2600785c029d.png)

I don't know if this is normal or if am doing something wrong. I will list out my config files and also the things I tried. 

## Config files

> rollup.config.js

![rollupConfigJs](https://user-images.githubusercontent.com/46924729/79116027-aa555f00-7d87-11ea-9dbf-59e97ae442e3.png)

> svelte.config.js

![svelteConfigJs](https://user-images.githubusercontent.com/46924729/79116037-b50ff400-7d87-11ea-887e-5467c892f857.png)

## Things I tried

* Reinstalled the Svelte VSCode Extension
* Directly linked the node path for the language server
* Added the `@import` directly into the style tag

If you have any further questions, please let me know.
Any help would be much appreciated! 😊🙏

**Comment by dummdidumm** [comment]
Do you have some marktetplace extension installed which may do your autocomplete in `.scss`-files but not in `.svelte`-files?

**Comment by nikbrunner** [comment]
Hi there,

thank you for responding. :) 

I have [SCSS Intellisense](https://github.com/mrmlnc/vscode-scss) installed. 

But I installed this Extension ( And now I am talking about this repository ) because it was recommended and saw in the description that it would provide autocompletion for SCSS.

> **CSS / SCSS / LESS**
> - Diagnostic messages for syntax and lint errors
> - Hover info
> - **Autocompletions** 👈
> - Formatting (via prettier)
> - Emmet
> - Color highlighting and color picker
> - Symbols in Outline panel

Did I misunderstand?

**Comment by dummdidumm** [comment]
Mhm this statement is probably a bit too bold then 😄 If you disable the SCSS Intellisense, do you lose the autocompletions you are asking for in SCSS files then, too? If so, I guess it's the SCSS Intellisense which does not know how to handle svelte files.
Adding this would then either have to be done in SCSS Intellisense ([like they did with vue](https://github.com/mrmlnc/vscode-scss/blob/f22688ebbc63782cdba1190f53724364b5faa669/src/utils/vue.ts)) or in the new [Svelte Beta Extension](https://github.com/sveltejs/language-tools). Since SCSS Intellisense already added vue-support, chances are good to get it in there. [I added a feature request over there](https://github.com/mrmlnc/vscode-scss/issues/115).

**Comment by nikbrunner** [comment]
Alright, I will look into it and get back to you. Thank you so much!
