### ISSUE TITLE
Provide sensible defaults for preprocessors

### ISSUE THREAD

**Issue by jamesbirtles** [UnwrittenFun/svelte-vscode#23]
Using style and script preprocessors continues to be a pain point for users as `svelte.config.js` is not properly documented, nor is it an expected solution.

We should provide sensible defaults for the preprocessors, but also allow as much customisation as the current solution.

**Comment by skflowne** [comment]
I'd like to help with this, could you give me some pointers or explain how you would fix it in case you already have a solution ?

**Comment by jamesbirtles** [comment]
@skflowne I was thinking bundling https://github.com/kaisermann/svelte-preprocess for example as it handles many preprocessors, however we would need to somehow allow people to override this in the svelte.config.js, and/or allow providing options to svelte-preprocess.

**Comment by skflowne** [comment]
So I'm not sure exactly where we're at with the `svelte.config.js`, the issue is still open on Svelte and I don't think it's mentioned in docs.
Is the goal to have all svelte related config in one place rather than in webpack or rollup ?
Would it be possible to pick the file from the project folder if it exists in order to override the extension config and if it doesn't exist take the default bundled one ?
