### ISSUE TITLE
Improve scss support

### ISSUE THREAD

**Issue by antony** [UnwrittenFun/svelte-vscode#28]
As per this issue: #16

Right now it seems like scss support largely works, but I get syntax errors in most of my components:

![scss 1](https://user-images.githubusercontent.com/218949/47708087-38d23100-dc25-11e8-9797-0cebb2858485.png)

![scss 2](https://user-images.githubusercontent.com/218949/47708129-50a9b500-dc25-11e8-8393-2b62d0e5ae6d.png)

I'm not sure I know enough about SCSS or how it is parsed to diagnose the exact issue, but it seems like there are elements of the SCSS syntax that the plugin does not yet understand.

**Comment by jamesbirtles** [comment]
You need to add a svelte.config.js for this in your project root. See example here https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-386102312

#23 will make this easier in the future

**Comment by antony** [comment]
@UnwrittenFun Ah fantastic - thanks, I'll give this a go.

**Comment by goranmandiccrs** [comment]
@antony Hi, have you managed to resolve this? I've tried following the instructions in #1 but couldn't quite get it to work

**Comment by stefanjarina** [comment]
I can confirm that works as I had the same issue today, however you could probably mention this in your README as searching for this "workaround" in issues is not user friendly.

Also I've used this package: https://github.com/kazzkiq/svelte-preprocess-scss
and added the required part in rollup.config.js.
that is basically when the errors occured for me.

Does this workaround in svelte.config.js effectively overwrite mentioned package functionality and simply uses node-sass directly instead of mentioned package? Just curious :-)

Anyway thanks for this awesome plugin.

**Comment by timbarclay** [comment]
I had trouble with this but eventually realised the solution given in #1 only supported the `<style type="text/scss">` case. To support the `<style lang="scss">` style, you need to amend the code in `svelte.config.js` a little to include `if (attributes.type !== "text/scss" && attributes.lang !== "scss") return;`.

A comment further down on #1 points this out, but I didn't originally scroll down that far.

**Comment by jamesbirtles** [comment]
There are now some SCSS specific[ docs available](https://github.com/UnwrittenFun/svelte-vscode/blob/0c7b92bbf25057cccad875eaef2da305e3e44e31/docs/preprocessors/scss.md) and I am going to use #23 to track having this work out of the box so I am closing this now 🙂
